server:
  port: 8010
  max-http-header-size: 1048576
  tomcat:
    max-http-post-size: 1048576
spring:
  application:
    name: aigou-common
  data:
    elasticsearch: 
      cluster-name: elasticsearch
      cluster-nodes: http://www.eureka-7001.com:9300 #9200是图形界面端,9300代码端 
eureka:
  client:
    service-url:
      defaultZone: http://www.eureka-7001.com:7001/eureka
  instance:
    prefer-ip-address: true